services:
  fastack-database:
    image: postgres
    hostname: database.fastack
    container_name: database
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "fastack"
      POSTGRES_PASSWORD: "fastack"
    ports:
      - "5432:5432"

  fastack-virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    hostname: virtuoso.fastack
    container_name: virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./virtuoso/data:/data
      - ./virtuoso/db:/opt/virtuoso/db
    ports:
      - "8890:8890"

networks:
  default:
    name: fastack
    driver: bridge

volumes:
  database:
  virtuoso:
